Bug: ALMA queries with lon, lat instead of RA, dec
astropy/astroquery pull request #1867
Opened 2020-10-22 23:29 UTC by keflavich

ALMA queries were using SkyCoord's string representation without converting to RA/Dec first.  This is a simple bugfix.

2020-10-23 03:32 UTC, bsipocz requested changes
A test and a changelog would be great

2020-10-23 03:37 UTC, bsipocz commented
Hmm, the travis failure looks related, the mock setup ne|lesseds some tweaking. 
Unfortunately the remote alma tests are failing so badly that it's difficult to be sure it's not causing any issues there, too.

2020-10-23 19:38 UTC, keflavich commented
@andamian , can you help out w/this?  I'll get to it if I can,  but the PR came as a side-effect of doing some proposal writing.

2020-10-23 20:07 UTC, andamian commented
> @andamian , can you help out w/this? I'll get to it if I can, but the PR came as a side-effect of doing some proposal writing.

Sure. Let me see what I can do.

2020-10-23 21:07 UTC, andamian commented
> > @andamian , can you help out w/this? I'll get to it if I can, but the PR came as a side-effect of doing some proposal writing.
> 
> Sure. Let me see what I can do.

At test_alma.py:252 it expects the query to be:
`select * from ivoa.obscore WHERE (INTERSECTS(CIRCLE('ICRS',**1.0**,2.0,1.0), s_region) = 1) AND calib_level>1 AND data_rights='Public'`
but instead is 
`select * from ivoa.obscore WHERE (INTERSECTS(CIRCLE('ICRS',**1.00001**,2.0,1.0), s_region) = 1) AND calib_level>1 AND data_rights='Public'`
This is likely due to to some extra computations. Same problem might pop up in other places and need to adjust (I don't know if the same rounded value will be obtained on other platforms). Do you want me to try to fix the issue?

2020-10-23 21:14 UTC, keflavich commented
Yes, please.    Perhaps for the test, we need to enforce some rounding?

2020-10-23 21:16 UTC, andamian commented
> Yes, please. Perhaps for the test, we need to enforce some rounding?

Do you know how can we do this?

2020-10-23 21:33 UTC, keflavich commented
Not without digging deeply - what is that first value?  RA? Dec? Radius in degrees?

2020-10-24 00:49 UTC, andamian commented
RA.

2020-10-26 17:04 UTC, andamian commented
I hope to find time this afternoon to look at it.

2020-12-04 03:56 UTC, pep8speaks commented
Hello @keflavich! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`astroquery/alma/tests/test_alma.py`](https://github.com/astropy/astroquery/blob/0646274d2f73603c19adadaac2498a50d5d6367d/astroquery/alma/tests/test_alma.py):

> [Line 377:1](https://github.com/astropy/astroquery/blob/0646274d2f73603c19adadaac2498a50d5d6367d/astroquery/alma/tests/test_alma.py#L377): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2020-12-24 20:41 UTC, merged