Remove `astroquery.utils.decorators`
astropy/astroquery pull request #2155
Opened 2021-09-23 13:04 UTC by eerovaher

The minimum required `astropy` version was updated in #1925, and that has made the `astroquery.utils.decorators` module obsolete.

2021-09-23 13:44 UTC, keflavich approved these changes

2021-09-28 00:12 UTC, bsipocz requested changes

2021-09-28 00:12 UTC, bsipocz commented on CHANGES.rst
> +- The functions ``astroquery.utils.decorators.deprecated()`` and
These never was part of the public API and was only internally used, so won't need a changelog.

https://astroquery.readthedocs.io/en/latest/utils.html?highlight=decorator

2021-09-28 00:12 UTC, bsipocz commented on astroquery/utils/decorators.py
> +from astropy.utils.decorators import (deprecated_renamed_argument
no need for this, the module is entirely for internal usage, remove it altogether rather than deprecate.

2021-09-28 16:04 UTC, bsipocz approved these changes

2021-09-28 16:04 UTC, merged

2021-09-28 16:04 UTC, bsipocz commented
Thanks @eerovaher!