Enable testing examples in `Gaia` documentation
astropy/astroquery pull request #2283
Opened 2022-02-04 18:26 UTC by eerovaher

The work done in #1973 that started enabling testing the code examples in `Gaia` documentation is finalized here. The examples that do not produce files and do not require logging in to the archive can now be tested.

2022-02-13 22:58 UTC, ceb8 requested changes
The testing part looks good. However, you've removed all import statements except those at the top, please put them back. The user needs to know what to import no matter where they jump into the documentation.

2022-02-14 22:23 UTC, ceb8 approved these changes

2022-02-15 22:30 UTC, bsipocz approved these changes

2022-02-15 22:30 UTC, bsipocz commented
Thanks @eerovaher!

2022-02-15 22:30 UTC, merged