Add query_regions to esa.hsa
astropy/astroquery pull request #2362
Opened 2022-04-15 20:02 UTC by keflavich

The ESA HSA tool should have a `query_regions` tool to match it to the general astroquery API.  This is my suggestion for how to do that.

It also passes on some kwargs that could be useful.

2022-04-15 20:02 UTC, pep8speaks commented
Hello @keflavich! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`astroquery/esa/hsa/core.py`](https://github.com/astropy/astroquery/blob/7bca6049c45c67a2af4cbe8e5795a8a26bd01f40/astroquery/esa/hsa/core.py):

> [Line 413:5](https://github.com/astropy/astroquery/blob/7bca6049c45c67a2af4cbe8e5795a8a26bd01f40/astroquery/esa/hsa/core.py#L413): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

2022-04-16 20:46 UTC, lvalerom requested changes
Looks good to me. I would add a test case for the new function in `hsa_test.py`:

```python
def test_query_region(self):
    c = SkyCoord(ra=100.2417*u.degree, dec=9.895*u.degree, frame='icrs')
    parameters = {'coordinate': c,
                  'radius': 0.5}
    dummyTapHandler = DummyHSATapHandler("query_region", parameters)
    hsa = HSAClass(self.get_dummy_tap_handler())
    hsa.query_region(**parameters)
    dummyTapHandler.check_call("query_region", parameters)
```

2022-04-16 20:46 UTC, lvalerom commented on astroquery/esa/hsa/core.py
> +        return self.query_hsa_tap(query, **kwargs)
Maybe here is cleaner to just call `query_region`:

```python
return self.query_region(coordinate, radius, n_obs=n_obs, columns="observation_id", **kwargs)
```

2022-04-16 20:46 UTC, lvalerom commented on astroquery/esa/hsa/core.py
> +
```suggestion
```

2022-04-16 20:48 UTC, keflavich commented
@lvalerom you can submit your suggested change as a PR onto this one.  That's the best way to make sure you get credit for those code changes.  Your suggestions are all good.

2022-04-17 16:46 UTC, lvalerom approved these changes

2022-04-19 17:18 UTC, bsipocz approved these changes

2022-04-19 17:18 UTC, bsipocz commented
OK, so including the narrative docs we have a decent 84% coverage including the query_region/observations methods, so I go ahead and merge this now.

Thank you both!

2022-04-19 17:18 UTC, merged