Refactored query criteria to use ehst.archive table
astropy/astroquery pull request #2524
Opened 2022-09-12 12:50 UTC by javier-ballester

Dear Astroquery team,

The query_criteria method in Hubble astroquery is using a complex query, joining three big tables and this makes its execution really slow. This query has been refactored to use only ehst.archive table, which contains all the criteria parameters.

Please let me know if any further changes are necessary.

Kind regards,

Javier

2022-09-12 12:57 UTC, keflavich approved these changes

2022-09-12 15:38 UTC, bsipocz requested changes
One minor thing with the changelog that I'm happy to fix myself prior merging. 

However, I now see a relevant doctest failure in docs/esa/hubble/hubble.rst (it maybe just the one it first stopped), please go through those as part of this PR. 

`python setup.py test -t docs/esa/hubble --remote-data`

2022-09-12 15:38 UTC, bsipocz commented on CHANGES.rst
> +hst
Inner refactorings with unchanged user API arent' usually mentioned in the changelog, but if the speed improvement is significant we can leave this here.
```suggestion
esa.hubble
```

2022-09-13 18:44 UTC, bsipocz approved these changes

2022-09-13 18:44 UTC, bsipocz commented
Thanks @javier-ballester!

2022-09-13 18:44 UTC, merged