GAIA: Update default Gaia data release to DR3
astropy/astroquery pull request #2596
Opened 2022-11-19 16:13 UTC by AlinderS

I updated the default data release for Gaia from DR2, released in April 2018, to DR3, released in June 2022.

2022-11-21 16:10 UTC, ceb8 approved these changes
LGTM

2022-11-21 17:01 UTC, bsipocz commented
I would ping @jespinosaar  and/or @mhsarmiento to sign off on this before merging it.

2022-11-21 17:13 UTC, eerovaher commented on docs/gaia/gaia.rst
> +  >>> Gaia.MAIN_GAIA_TABLE = "gaiadr2.gaia_source"  # Select early Data Release 2
```suggestion
  >>> Gaia.MAIN_GAIA_TABLE = "gaiadr2.gaia_source"  # Select Data Release 2
```

2022-11-21 17:19 UTC, bsipocz requested changes
I see failing remote doctests, those should be fixed prior merging.

(basically, locally a `python setup.py test -P gaia -R` should pass, too, even if CI is all green)

2022-11-21 19:31 UTC, AlinderS commented
I'll admit I don't know why that test failed. The text that was fine was copied in the same way as the text that failed. 
Regardless, it's fixed now. Thanks for the assistance!

2022-11-27 08:06 UTC, bsipocz approved these changes

2022-12-12 03:22 UTC, bsipocz commented
Rebased to resolve the recent docs changes. And given no objections were received I'm going ahead and merge this now.

Thanks @AlinderS!

2022-12-12 03:27 UTC, merged