Adding error handling examples to mast docs
astropy/astroquery pull request #2736
Opened 2023-05-12 15:08 UTC by mstcyr2

Error handling examples to show users how to avoid/fix possible input-based errors.

2023-05-31 17:28 UTC, bsipocz commented on docs/mast/mast.rst
> +.. doctest-skip::
Do not skip these tests, doctest can handle checking exceptions and warnings, you need to insert the actual error you see to make the test pass (there are some examples scattered over the docs)

2023-06-02 03:21 UTC, mstcyr2 commented on docs/mast/mast.rst
> +parameter will result in an error when set to 'TICA'.
When I ran this example it gave an error and not a warning.

2023-06-07 20:13 UTC, jaymedina commented on docs/mast/mast.rst
> +   UnitTypeError: Longitude instances require units equivalent to 'rad', but no unit was given.
Not sure if you need this example since this is an error handling case for `SkyCoord` and not `astroquery.mast`. This is slightly out of scope.

2023-06-07 20:15 UTC, jaymedina commented on docs/mast/mast.rst
> +The `~astroquery.mast.CatalogsClass.query_object` method for positional queries
I think this example might be too basic for our target audience. I don't see them running into this error.

2023-06-07 20:20 UTC, jaymedina commented on docs/mast/mast.rst
> +The 'params' parameter for the `~astroquery.mast.MastClass.service_request` method requires a key-value pair
Update this example to reference this page: https://mast.stsci.edu/api/v0/_services.html 

Mention that other services (particularly JWST services) require 2 principal keywords before the actual params (and those are `columns` and `filters` - see link above for more context.

2023-06-27 19:07 UTC, jaymedina requested changes
Some small edits to existing examples. I suggest removing one of the examples entirely, but feel free to keep it if you feel like it's justifiable. Good work!

2023-06-27 19:07 UTC, jaymedina commented on docs/mast/mast.rst
> +"MatchID" is case sensitive in this case, and will produce an error with different
I'd remove this example, since I think most users know that the metadata is case-sensitive.

2023-06-27 19:07 UTC, jaymedina commented on docs/mast/mast.rst
> +Many mast services, specifically JWST and Catalog services, require the two principal keywords, columns and filters,
I would put quotes around the keyword names, so formatted like this: _require the two principal keywords, "columns" and "filters", to list parameters_

2023-06-27 19:07 UTC, jaymedina commented on docs/mast/mast.rst
> +addition to columns and filters or on their own. For example, the Cone search service only requires the 'ra' and
No need to capitalize "Cone"

2023-07-03 18:06 UTC, mstcyr2 commented
@bsipocz I think this is ready to merge. Let me know if you have any other suggestions for this. Thanks!

2023-07-06 22:34 UTC, bsipocz reviewed
All the examples cause test failures as the tracebacks are not properly added to the docs. I'll just quickly push a commit and fix it. I'll also rebase to be sure we're all good as there have been a few other PRs since this was branched out, that modified this documentation page.

 For the next time, I would suggest to run the remote tests until they are all clean (for this particular case `pytest docs/mast -R`)

2023-07-06 22:34 UTC, bsipocz commented on docs/mast/mast.rst
> +   >>> obs_table = Observations.query_object("M8",".02 deg")
This produces a test failure as the error is not exactly copy pasted.

2023-07-06 22:57 UTC, bsipocz commented
@jaymedina - the following isn't issue the warning any more, so I also removed that as part of this PR to make sure all the docs is passing:

```
    >>> from astroquery.mast import Tesscut
    >>> sector_table = Tesscut.get_sectors(objectname="Ceres", moving_target=True)
```

2023-07-06 23:02 UTC, merged

2023-07-06 23:03 UTC, bsipocz commented
Thanks @mstcyr2!