Refactor Skyview module to use pyVO's SIAP
astropy/astroquery pull request #2849
Opened 2023-10-09 21:44 UTC by duytnguyendtn

Hello Astroquery Maintainers!

This PR offers to refactor the Skyview module, currently webscraping parameters using our Perl script to instead use the Virtual Observatory's Simple Image Access Protocol via the pyVO package. Feedback and suggestions would be highly welcome!

There were some notable changes that I made that is different from the original Skyview class, including:
1. The reported parameters the Skyview surveys support are much smaller in scope than the full capabilities of the original Astroquery Skyview package. Removed parameters include: the `resolver`, `deedger`, `lut`, `grid`, and `gridlabels` arguments. (Commit bd6864c4b4faeb13357607fa82d4f88539043051)
2. The online Perl form only supports specifying the size of the FOV in degrees, rather than through width and height. Because the Astroquery spec states only one is required, I brought the skyview API in line with the Perl script and only provided `radius` as a parameter, dropping the width/height args. (Commit 9e83dd0a69f8b4e01ac22c3c1f64872943ca753c)
3. To make it more explicit, I renamed the `survey` arg to `surveys` (with an s) to indicate the user may specify multiple surveys.

Tests have been updated as well, though I did run into an issue with one of the remote tests, where the download is timing out, but there is no way for us to override the timeout from the level of the astroquery module. I reported it in #astroquery on slack (copied here for reference):

<details>

Hi all, undergoing a similar effort as Brigitta and refactoring the SkyView class to use pyVO's SIA. I'm hitting a timeout error trying to download the FITS files from one of our larger archives to open them with `astropy.io.fits`. I'm using `astroquery.utils.commons.FileContainer.get_fits` , but there doesn't seem to be a way to control the timeout. Is the recommended way to handle this the same way `astroquery.besancon` does and call `astroquery.utils.commons.get_readable_fileobj` directly to [handle the timeout manually](https://github.com/astropy/astroquery/blob/8fe1a8b283905796e8a3da1f7765fcd7912d0b92/astroquery/besancon/core.py#L114-L144), or is there a better way?

</details>

This PR is still in draft until I complete the documentation changes.

2023-10-09 21:44 UTC, pep8speaks commented
Hello @duytnguyendtn! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`astroquery/skyview/tests/test_skyview.py`](https://github.com/astropy/astroquery/blob/7ccc74ff615355a8f8c9bded7ee70e8046d396f4/astroquery/skyview/tests/test_skyview.py):

> [Line 34:284](https://github.com/astropy/astroquery/blob/7ccc74ff615355a8f8c9bded7ee70e8046d396f4/astroquery/skyview/tests/test_skyview.py#L34): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment

2023-10-09 22:08 UTC, bsipocz reviewed
@duytnguyendtn  - Thanks for the PR.

There are a lot of code back and forth in the commit history, I don't think it has any benefits to keep those duplicated classes around. Could you please squash them out?

Besides that, as the first round I left some minimal comments, will come back at a deeper look when you flip it out from the draft status. 

For the kwarg deprecations, have a look into the IRSA module and its usage of `deprecated_renamed_argument`.

2023-10-10 21:08 UTC, duytnguyendtn commented on astroquery/skyview/tests/test_skyview_remote.py
> +from . import ETA_CARINAE_MULTI_CASE_ARGS, ETA_CARINAE_SINGLE_CASE_ARGS
Done! I originally put this here thinking I would also use the same usecase for my local tests, but once I mocked up the entire response, this wasn't necessary

2023-10-10 21:09 UTC, duytnguyendtn commented on astroquery/skyview/core.py
> -        resolver : str
Thanks for the reference to the IRSA code. I think I addressed this properly!

2023-10-10 21:09 UTC, duytnguyendtn commented on astroquery/skyview/core.py
> +        surveys : str or list of str
Reverted!

2023-10-12 17:22 UTC, duytnguyendtn commented
@bsipocz Thanks for the comments! I think I addressed them and my documentation changes, so this PR should be ready for a full review. Thank you in advance!

Also pinging @zoghbi-a, another HEASARC member who may be interested in taking a look

2023-11-02 19:38 UTC, duytnguyendtn commented
@bsipocz Any sense of when we might be able to get a review on this PR? Thanks!

2023-11-02 20:44 UTC, keflavich reviewed
This looks like a significant improvement in that it simplifies the interface and uses a supported API.  Does it fully replicate the old functionality?  At least some keywords, like `width` and `height`, are no longer supported.  The docs should at least give some clue about the difference between the web interface and the new API.

2023-11-02 21:28 UTC, duytnguyendtn commented
Thanks for the comments @keflavich! Sadly no, this does not fully replace the old API due to the SIAP parameters not being a 1-1 match to the ones available via the online perl form. As per https://github.com/astropy/astroquery/pull/2849#discussion_r1350816301, I tried to properly deprecate them on the code side and explicitly list the supported parameters in the documentation in https://github.com/astropy/astroquery/pull/2849/commits/2a6135a3d410ff6c023b793f4b1e4444a69387fa.

Would it be appropriate to explicitly list the parameters being removed in a warning? Or are you instead thinking of a smaller guiding the user's attention to the difference in available parameters?

2023-11-02 23:29 UTC, keflavich commented
The deprecation strategy will already do that, but I'm concerned: if we're losing functionality, then we shouldn't just straight up replace the old code; instead, these should live side-by-side.

However, it's not entirely clear to me that we do lose functionality. Yes, we lose keywords, but do those keywords have equivalents in SIAP?  i.e., can the same images be retrieved with a different set of keywords?  If so, we should provide users with at least some examples of how that would look.

2023-11-17 15:57 UTC, zoghbi-a commented on astroquery/skyview/core.py
> +            registry_results = registry.search(ivoid=self._survey_dict[current_survey]['ivoid'])
I don't think there is a need for another call to the registry here. During the first call in `_survey_dict`, you can also save `access_url`, and then use it here to create the ` sia_service` by something like: ` sia_service  = pyvo.sia.SIAService(self._survey_dict[current_survey]['access_url'])`

2024-01-28 18:41 UTC, bsipocz requested changes
The big review point here is to remove all, or at least some of the registry calls. It adds complexity and we don't really need to do multi-archive data discovery here, but only plan to do the skyview services.

For both other cases where we do a `query_sia`, we do that directly, without doing any registry search. Could we follow it here, too rather than the more complex workflow of calling the registry and then do the search?

I would ping @andamian here to see whether he agrees as the alma module has the functionality the longest.

2024-03-19 20:58 UTC, duytnguyendtn commented
Hi all, thanks for your patience! Coming back to this after a bit of hiatus, I spoke with members of the HEASARC regarding how to move forward and we think we'd like to refactor our SIA service on our end first to support the missing arguments described here. Because a lot of the deprecation work that was added to this branch won't be needed (and we don't have a timeline to when this SIA work will be complete), I'm going to close this PR to get this off of your radar and reintroduce it once we (A) finish supporting the missing arguments and (B) I address the above comments the Astroquery team has made.

Thanks again! I'll be back with a second attempt at this!

2024-03-19 20:58 UTC, closed without merging