GAIA: include table size in the class TapTableMeta
astropy/astroquery pull request #2970
Opened 2024-03-17 15:38 UTC by cosmoJFH

User tables do not display information on their physical size on disk. This makes account of the user quota difficult. That attribute should be visible to Astroquery users.

A new test was made.

cc @esdc-esac-esa-int 

Jira: GAIAPCR-1036

2024-03-19 02:07 UTC, bsipocz requested changes
The test data file needs to be trimmed, otherwise this looks all OK. 

Thanks!

2024-03-19 07:59 UTC, cosmoJFH commented on astroquery/utils/tap/xmlparser/tests/test_xmlparser.py
> +def __check_table(table, qualifiedName, numColumns, columnsData, size_bytes=-1):
I agree with you. I've updated the default value to None.

2024-03-19 08:00 UTC, cosmoJFH commented on astroquery/utils/tap/xmlparser/tests/data/test_tables_gaia.xml
I trimmed the file, since the entire file was not required for test.

2024-03-19 08:06 UTC, cosmoJFH commented on CHANGES.rst
> +- Include table size in the class TapTableMeta returned by the functions load_tables and load_table, in the class Tap.
I don't understand where should I include this information.

2024-03-19 15:04 UTC, bsipocz commented on CHANGES.rst
> +- Include table size in the class TapTableMeta returned by the functions load_tables and load_table, in the class Tap.
There is an almost empty 0.4.8 section at the very top of the file, but I can move this one (and those from your other PRs right before merging them)

2024-03-20 10:38 UTC, cosmoJFH commented on CHANGES.rst
> +- Include table size in the class TapTableMeta returned by the functions load_tables and load_table, in the class Tap.
Thanks for you answer. I included the information for the PR in the section you told me.

2024-03-23 18:54 UTC, cosmoJFH commented
We have reviewed the comments in https://github.com/astropy/astroquery/issues/2863 and we would like to use this PR to updated the documentation for the functions load_table and load_tables.

2024-04-06 03:53 UTC, bsipocz approved these changes
I went ahead and rebased the PR to squash the commits about the new file together, so the big one doesn't end up in the git history.

Merging it now if CI is all green.

Thanks!

2024-04-06 03:57 UTC, merged