fix `MOLWT` column starting position
astropy/astroquery pull request #3094
Opened 2024-09-18 17:12 UTC by kmaitreys

Now the molecule tag `100501` and others work. Earlier they were crashing with 
```python
ValueError: invalid literal for int() with base 10: '13-'
```
Because that `-` is part of the signed `TAG`.

2024-09-18 18:00 UTC, bsipocz commented
RTD failure is unrelated and will be fixes outside this PR.

2024-09-19 02:43 UTC, keflavich commented
We'll need some tests for this error.  I can confirm that 100501 does not work right now:
```python
CDMS.query_lines(10*u.GHz, 100*u.GHz, molecule='100501', parse_name_locally=False)
```

I tested one other case, and it worked both before & after:
```python
CDMS.query_lines(10*u.GHz, 100*u.GHz, molecule='HCCCN', parse_name_locally=True)
```
so I'm going to approve this, but on my to-do list is to systematically test all molecules for failures like this.

2024-09-19 02:43 UTC, keflavich approved these changes

2024-09-19 06:14 UTC, bsipocz commented
In addition to putting it on the to-do, please do open an issue for it here, too.

2024-10-17 23:23 UTC, bsipocz requested changes
Test failures are related

2024-10-18 03:39 UTC, kmaitreys commented
Yeah, I'm sorry, the last commit I pushed actually broke a bunch of other molecules. So far from my testing/debugging, it looks like just changing the column numbers will not help, because the format itself is not consistent for all molecules. It needs a bit larger refactor in some parts.

I'm still up for fixing this, but couldn't due to my own work. If it's possible, I would like this to be kept open for a few weeks more.

2025-01-17 17:09 UTC, closed without merging